# Makefile for operator

.PHONY: build deploy test

build:
	# TODO: Build operator image
	echo "Building operator..."

deploy:
	# TODO: Deploy operator
	kubectl apply -f config/

test:
	# TODO: Run tests
	pytest tests/
