apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "model-api.fullname" . }}
  labels:
    {{- include "model-api.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
